---
# tasks file for influxdb
- name: Install influxdb repository
  yum_repository:
    name: influxdb
    description: influxdb repository
    baseurl: https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
    gpgkey: https://repos.influxdata.com/influxdb.key
    gpgcheck: yes

- name: install telegraf
  yum:
    name: 'telegraf-{{ telegraf_version }}'
    state: present
    update_cache: yes

- name: enable and start telegraf service
  systemd:
    name: telegraf
    state: started
    enabled: yes

- name: create config file
  include: config_file.yml

- name: configure log file path 
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: agent
    option: logfile
    value: "'{{ telegraf_agent_logfile }}'"
    backup: yes 
  notify:
  - restart telegraf


- name: configure debug
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: agent
    option: debug
    value: "{{ telegraf_agent_debug }}"
    backup: yes 
  notify:
  - restart telegraf

- name: configure influxdb output
  include: outputs/influxdb.yml