---
# tasks file for influxdb
- name: Install influxdb repository
  yum_repository:
    name: influxdb
    description: influxdb repository
    baseurl: https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
    gpgkey: https://repos.influxdata.com/influxdb.key
    gpgcheck: yes

- name: install telegraf
  yum:
    name: 'telegraf-{{ telegraf_version }}'
    state: present
    update_cache: yes

- name: enable and start telegraf service
  systemd:
    name: telegraf
    state: started
    enabled: yes

- name: configure log file path 
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: agent
    option: logfile
    value: "'{{ telegraf_agent_logfile }}'"
    backup: yes 
  notify:
  - restart telegraf


- name: configure debug
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: agent
    option: debug
    value: "{{ telegraf_agent_debug }}"
    backup: yes 
  notify:
  - restart telegraf

- name: configure influxdb urls
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: '[outputs.influxdb]'
    option: urls
    value: "{{ telegraf_outputs_influxdb_urls }}"
    backup: yes 
  notify:
  - restart telegraf

- name: configure influxdb database name
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: '[outputs.influxdb]'
    option: database
    value: '"{{ telegraf_outputs_influxdb_database }}"'
    backup: yes 
  notify:
  - restart telegraf

- name: configure influxdb username
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: '[outputs.influxdb]'
    option: username
    value: '"{{ telegraf_outputs_influxdb_username }}"'
    backup: yes 
  when: not((telegraf_outputs_influxdb_username is undefined) or (telegraf_outputs_influxdb_username is none) or (telegraf_outputs_influxdb_username | trim == '') )  
  notify:
  - restart telegraf

- name: remove influxdb username
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: '[outputs.influxdb]'
    option: username
    backup: yes 
    state: absent
  when: (telegraf_outputs_influxdb_username is undefined) or (telegraf_outputs_influxdb_username is none) or (telegraf_outputs_influxdb_username | trim == '')
  notify:
  - restart telegraf  


- name: configure influxdb password
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: '[outputs.influxdb]'
    option: password
    value: '"{{ telegraf_outputs_influxdb_password }}"'
    backup: yes 
  when: not((telegraf_outputs_influxdb_password is undefined) or (telegraf_outputs_influxdb_password is none) or (telegraf_outputs_influxdb_password | trim == '') )  
  notify:
  - restart telegraf

- name: remove influxdb password
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: '[outputs.influxdb]'
    option: password
    backup: yes 
    state: absent
  when: (telegraf_outputs_influxdb_password is undefined) or (telegraf_outputs_influxdb_password is none) or (telegraf_outputs_influxdb_password | trim == '')
  notify:
  - restart telegraf  